# Generated by Django 6.0 on 2026-01-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('tools', 'Tools'), ('cattle', 'Cattle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(upload_to='market/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.CharField(max_length=100),
        ),
    ]
