# Generated by Django 6.0 on 2026-01-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_market', '0002_alter_listing_category_alter_listing_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cattle_type',
            field=models.CharField(blank=True, choices=[('cow', 'Cow'), ('buffalo', 'Buffalo'), ('ox', 'Ox'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
