# Generated by Django 6.0 on 2026-01-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_market', '0003_listing_cattle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tool_type',
            field=models.CharField(blank=True, choices=[('vehicles', 'Vehicles'), ('machinery', 'Machinery'), ('instruments', 'Instruments'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
