# Generated by Django 6.0 on 2025-12-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandiPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_key', models.CharField(max_length=50)),
                ('crop_name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('source', models.CharField(default='agmarknet', max_length=50)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'crop_key'],
                'indexes': [models.Index(fields=['crop_key'], name='mandi_mandi_crop_ke_bd2cd1_idx'), models.Index(fields=['state'], name='mandi_mandi_state_4a9f60_idx'), models.Index(fields=['district'], name='mandi_mandi_distric_ba2365_idx'), models.Index(fields=['date'], name='mandi_mandi_date_cbd5f4_idx')],
            },
        ),
    ]
